apiVersion: apps/v1
kind: Deployment
metadata:
  name: demodeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      myapp: demo
  template:
    metadata:
      labels:
        myapp: demo
    spec:
      containers:
      - name: demo-container
        image: 218137097139.dkr.ecr.ap-south-1.amazonaws.com/demo-app:latest
        ports:
        - containerPort: 80
